# Generated by Django 5.2.7 on 2025-10-23 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogstats_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogstats',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='blog',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
