# Generated by Django 5.2.7 on 2025-10-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogstats_liked_users_blog_liked_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogstats',
            name='likes',
        ),
    ]
