# Generated by Django 5.2.7 on 2025-10-23 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogstats_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstats',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_blogs_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
