# Generated by Django 5.2.7 on 2025-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogstats_liked_users_alter_blog_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstats',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
